baseURL = "https://vinhphamthanh.dev/"
# language code
defaultContentLanguage = 'en'
languageCode = "en"
title = "vinhphamthanh.dev"

# Change the default theme to be use when building the site with Hugo
theme = "DoIt"

[languages]
  [languages.en]
    languageName = 'English'
    languageCode = 'en'
  [languages.vi]
    languageName = 'Vietnamese'
    languageCode = 'vi'

[params]
  # DoIt theme version
  version = "0.4.X"
  [params.header]
    # DoIt NEW | 0.2.11 Theme change mode
    # theme change mode ("switch", "select")
    themeChangeMode = "switch"
    # DoIt NEW | 0.2.0 Header title config
    [params.header.title]
      # URL of the LOGO
      logo = ""
      # title name
      name = "vinhphamthanh.dev"
      # you can add extra information before the name (HTML format is supported), such as icons
      pre = ""
      # you can add extra information after the name (HTML format is supported), such as icons
      post = ""
      # DoIt NEW | 0.2.5 whether to use typeit animation for title name
      typeit = true
  [params.typeit]
    # typing speed between each step (measured in milliseconds)
    speed = 100
    # blinking speed of the cursor (measured in milliseconds)
    cursorSpeed = 5000
    # character used for the cursor (HTML format is supported)
    cursorChar = "|"
    # cursor duration after typing finishing (measured in milliseconds, "-1" means unlimited)
    duration = -1

  [params.page]
    [params.page.comment]
      enable = true
      [params.page.comment.giscus]
        enable = true
        # owner/repo
        dataRepo = "vicyan1611/vinhphamthanh.dev-comments"
        dataRepoId = "R_kgDOMp5Obw"
        dataCategory = "General"
        dataCategoryId = "DIC_kwDOMp5Ob84CiB0J"
        dataMapping = "pathname"
        dataStrict = "0"
        dataReactionsEnabled = "1"
        dataEmitMetadata = "0"
        dataInputPosition = "bottom"
        lightTheme = "light"
        darkTheme = "dark"
        dataLang = "en"
        dataLoading = "lazy"

# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false
