[footer]
  enable = true
[page]
  [page.commment]
    enable = true
    [page.comment.giscus]
        enable = true
        # owner/repo
        dataRepo = "vicyan1611/vinhphamthanh.dev-comments"
        dataRepoId = "R_kgDOMp5Obw"
        dataCategory = "General"
        dataCategoryId = "DIC_kwDOMp5Ob84CiB0J"
        dataMapping = "pathname"
        dataStrict = "0"
        dataReactionsEnabled = "1"
        dataEmitMetadata = "0"
        dataInputPosition = "bottom"
        lightTheme = "light"
        darkTheme = "dark"
        dataLang = "en"
        dataLoading = "lazy"
